/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dbc.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class PerguntasCriadas extends javax.swing.JFrame {

    String textoPergunta;
    String alternativaCorreta;
    String alternativaA;
    String alternativaB;
    String alternativaC;
    String alternativaD;
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet adicionar = null;

    public void fase1() {
        try {
            String sql = "Select idQuestão,tipoQuestão, perguntaQuestão, AlternativaCorreta, AlternativaA, AlternativaB, AlternativaC, AlternativaD, dificuldadeQuestão from Questõens where idQuestão = 21 ";
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                textoPergunta = (rs.getString(3));
                alternativaCorreta = rs.getString(4);
                alternativaA = (rs.getString(5));
                alternativaB = (rs.getString(6));
                alternativaC = (rs.getString(7));
                alternativaD = (rs.getString(8));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    public void fase2() {
        try {
            String sql = "Select idQuestão,tipoQuestão, perguntaQuestão, AlternativaCorreta, AlternativaA, AlternativaB, AlternativaC, AlternativaD, dificuldadeQuestão from Questõens where idQuestão = 22 ";
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                textoPergunta = (rs.getString(3));
                alternativaCorreta = rs.getString(4);
                alternativaA = (rs.getString(5));
                alternativaB = (rs.getString(6));
                alternativaC = (rs.getString(7));
                alternativaD = (rs.getString(8));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    public PerguntasCriadas() {
        initComponents();
        initComponents();
        conexao = ModuloConexao.conector();
        System.out.println(conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 330, 180));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Começar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 440, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Começar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int pontuacao = 0;
       

        //PERGUNTA DE NUMERO 1//
      fase1();

        String rP2 = JOptionPane.showInputDialog("\n Sua pontuação é de :" + pontuacao + "\n Pergunta = " + textoPergunta + "\n \n \n \n A ." + alternativaA + "\n \n B ." + alternativaB
                + "\n \n C ." + alternativaC
                + "\n \n D ." + alternativaD
                + "\n \n");
        JOptionPane.showMessageDialog(null, "Uma segunda autenticação é necessaria!! \n Porfavor insira seus dados");

        String tstLogin = JOptionPane.showInputDialog("Login:");
        String tstSenha = JOptionPane.showInputDialog("Senha:");
        String tstRa = JOptionPane.showInputDialog("Ra:");

        if (rP2.equals(alternativaCorreta)) {
            JOptionPane.showMessageDialog(null, "Resposta Correta");
            pontuacao = pontuacao + 75;
            JOptionPane.showMessageDialog(null, "Seu resultado final foi de:" + pontuacao + "\n Parabéns");
            try {
                String sql = "insert into Ranking(loginUsuário,pontuaçãoUsuario,raUsuário)VALUES(?,?,?)";
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tstLogin);
                pst.setInt(2, pontuacao);
                pst.setString(3, tstRa);

                int rs = pst.executeUpdate();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Resposta Incorreta");
            try {
                String sql = "insert into Ranking(loginUsuário,pontuaçãoUsuario,raUsuário)VALUES(?,?,?)";
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tstLogin);
                pst.setInt(2, pontuacao);
                pst.setString(3, tstRa);

                int rs = pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            JOptionPane.showMessageDialog(null, "Seu resultado final foi de:" + pontuacao + "\n Parabéns");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerguntasCriadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerguntasCriadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerguntasCriadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerguntasCriadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerguntasCriadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
